### ISSUE TITLE
conveyor height wrong on first link when starting in elevated positon

### ISSUE THREAD

**Issue by catonthekbd** [Algalish/SmartIssueTracker#101]
I dropped a couple of splitters to get correct height

I then tried to drop 5 splitters on 3rd level
1st conveyour was on 2nd level
![Screenshot20210123-16070900000](https://user-images.githubusercontent.com/57501659/105626775-f9a5e100-5e29-11eb-8dce-aca1f968c557.png)

**Comment by Algalish** [comment]
@catonthekbd  Can you try the same with this test version?
https://we.tl/t-ApjeWJXqKb

**Comment by catonthekbd** [comment]
no change ...
![Screenshot20210124-10550400000](https://user-images.githubusercontent.com/57501659/105628117-e0556280-5e32-11eb-8a87-0cf8fe0d8897.png)

**Comment by catonthekbd** [comment]
went back and re-checked - update info screen still says it is v.14, even though correct .smod file is in mod directory

**Comment by Algalish** [comment]
@catonthekbd  Tryed everything that I possibly could to fix this today but no luck. Due to all the hacks I have with those belts - this is not working properly.
For now just remove the first belt and build it manually, I will keep the issue open and I will get back to it later.

P.S. It is ok that test version is showing V14: I only update the texts and version number before "release"

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
