### ISSUE TITLE
Request to build with lifts

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartIssueTracker#125]
https://media.discordapp.net/attachments/777233974878797895/812611904467894312/unknown.png?width=1155&height=650

**Comment by Vassi** [comment]
+1, I feel like there's a lot of ways to skin this cat and I'm not sure you can make everyone happy. For instance, I like to put three splitters on the left belt and then make the lift face towards it.

For now, I've had to turn off auto-connect when connecting a bunch of assemblers because I just end up having to delete a lot of splitters and stuff and it gets messy.

Small price to pay for everything else SMART does, though, thank you for all your work!

**Comment by Algalish** [comment]
I am closing all the open issues because old issues may not require any action. 
But if this is still something you need or if this is something that is not working in the latest version in U6 - please reopen the issue and I will look into it.
Thank you
