### ISSUE TITLE
Can't Rotate Foundation Block Anymore [HOLD mode question]

### ISSUE THREAD

**Issue by SextonKing** [Algalish/SmartIssueTracker#13]
Ever since the update, the blocks are now fixed in one orientation and cannot be rotated at all. This mod can't be used until that's fixed.

**Comment by SextonKing** [comment]
Also, can't seem to move the block once you set it. You have to completely cancel out of the foundation build and then re-start the process and re-place the block where you want it, then start all over. If you try to use the mod like it worked previously, it won't rotate and it won't move to another location with the build tool pointer. Basically the mod is broken now.

**Comment by EricHamby** [comment]
Agreed, Cant rotate blocks since update.

**Comment by Algalish** [comment]
@EricHamby @SextonKing 
Hey guys!
This is actually a new feature called HOLD mode. You can fly around the foundation and preview the result instead of just blindly build. That mode also helps building in the sky.
Once you do something for the foundation - this mod turns on automatically.
You can always exit this mode by pressing "H" (Hold)

P.S. You should read mod update texts - I really try to expain everything there.
P.P.S. Do you think this mode should not be turned on automatically or once you understand how to use it - it's fine?

**Comment by Algalish** [comment]
I will leave this issue open for people to vote about the need to leave this mode on automatically.

**Comment by SextonKing** [comment]
Yeah, I DID read the documentation, which apparently wasn't very clear. The best way, at least IMO, is to leave a feature as an addition to what already works. The way you had the mod initially set up to work with SHIFT to hold and scroll wheel to rotate was fine. You've updated the text now on the mod page at Ficsit, but earlier it wasn't very clear at all. Thanks for clarifying.

**Comment by SextonKing** [comment]
If you'd like to really tweak things to improve the mod, you could leave its core function alone for now and just fix the things that have already been reported as difficult, like the fact that you've assigned LEFT ALT as a width key but LEFT ALT is also the key on Pak Utility Flight Mode for descending. I can't use the function with the other mod solely because we can't reassign keys in your mod for that function. Or the arrow indicator superimposed over the block so we can more readily see how the piece will be oriented without a bunch of rotating and trial-and-error. Thanks!

**Comment by Algalish** [comment]
@SextonKing  Thx for the feedback.
Since the mod is not "released" yet and is in its early development stage - that means that at any point some things may change for the better (at least a version of it that I think is best).
But turning hold mode automatically was not a very good idea and I will probably disable it in the next update. Several people at discord also suggested that.

btw what is the alternative to LEFT ALT, what do you think fits best for that action?

**Comment by kenjura** [comment]
Yeah, +1 to hold mode off by default. Or it should be toggled. For me, every time I place a foundation, it returns to "on". If it were globally on or off based solely on pressing H (or restarting the game, natch) that would work better, at least in my opinion. Still, amazing mod, absolutely essential.

**Comment by Algalish** [comment]
Have an idea: If the rotation will start working in HOLD mode, is this ok to leave it in automatic mode?

The logic of automatic mode  is simple: if you press shift or any other key by mistake and then let go - hold will not turn on.
But if you change something while holding a shift key or any other key - then it will be on.
So I think as long as rotations is working - this can stay like this.

But what do you guys think?

@kenjura  @EricHamby  @SextonKing 

P.S. in the future stuff like that could be configured using a UI and saved to the config file. same as key bindings. but thats not something that I can implement tomorrow.

**Comment by Algalish** [comment]
fyi: too many people asked about disabling this.  update 0.4.1 is uploaded and waiting a review from moderators.

**Comment by EricHamby** [comment]
Sorry im at work and dont have the time to dig into the user guide but rotate is still working? Just different?

**Comment by Algalish** [comment]
@SextonKing  @EricHamby  Auto-hold mode can be turned on in settings . this time with arrows is so easy to use. point, rotate and then start doing stuff and it will hold. let me know if you guys like it or what I need to improve.
