### ISSUE TITLE
Twirl is not working

### ISSUE THREAD

**Issue by tonyorell95** [Algalish/SmartIssueTracker#147]
when twirling it offset the whole block instead of each individual piece

**Comment by stefanrusso** [comment]
I'm experiencing this same issue.  Instead of all blocks being shifted relative to the blocks they're attached to, only the "root" block stays in place and everything else shifts as a whole.

![20210425111115_1](https://user-images.githubusercontent.com/1565266/115998834-2a2b2180-a5b7-11eb-9daa-0f2cda024b3a.jpg)

**Comment by Algalish** [comment]
hold on there guys, will fix in the next update

**Comment by JKamsker** [comment]
Any plans when said update is scheduled?

**Comment by Algalish** [comment]
@JKamsker probably at the end of this weekend

**Comment by Algalish** [comment]
fixed in 16.3.1
