### ISSUE TITLE
3D smart evreything?

### ISSUE THREAD

**Issue by wchenaf** [Algalish/SmartIssueTracker#40]
Since now you have done the P for spacing, is it possible to add the third direction for smart building especially for stackable poles?

**Comment by wchenaf** [comment]
And I wonder if you feel like sharing your source code. I feel itchy to start modding and make your mod into “smart building” working for splitters😬😬

**Comment by Algalish** [comment]
@wchenaf  Yea, third direction is a good idea and I am thinking about it. Do you have an idea for a key that would be good for the third dimension? Probably Ctr. So it will be Shift for X, Alt for Y and Ctrl for Z.

Take a look at my latest video: there is a secret spoiler about Smart Buildings ;)
They will probably be in the next update.

And take a look at another spoiler for Smart Splitters. As it turned out: its insanely hard to "snap" hologram to hologram and the game is not designed for that as Archengius (the biggest guru of C++ modding for Satisfactory) said to me. But I f###ing got it working after days of trial and error and a lot of hacks.

![Screenshot_22](https://user-images.githubusercontent.com/1682176/98827480-fc5a8200-2447-11eb-8777-e9b94ea09162.png)

**Comment by Algalish** [comment]
As per source code: at first I thought that I was going to open it up for public but after spending more than 10000$ worth of my time working on the mod I don't feel the same way anymore. My apologies for that  but I will be honest with you:  I plan to take a monopoly for making all the buildings "Smart" in game. Of course you can try to do it better if you like, it's a free world. But there are so many things that can be improved in Satisfactory apart from that if you know what I mean.  And if you are just started modding: here are a few amazing repositories that you can read and understand how to do stuff.   https://github.com/TwoTwoEleven/MicroManage  and https://github.com/CoderDE/FicsIt-Networks

**Comment by Algalish** [comment]
@wchenaf 
As per source code: at first I thought that I was going to open it up for public but after spending more than 10000$ worth of my time working on the mod I don't feel the same way anymore. My apologies for that but I will be honest with you: I plan to take a monopoly for making all the buildings "Smart" in game. Of course you can try to do it better if you like, it's a free world. But there are so many things that can be improved in Satisfactory apart from that if you know what I mean. And if you are just started modding: here are a few amazing repositories that you can read and understand how to do stuff. https://github.com/TwoTwoEleven/MicroManage and https://github.com/CoderDE/FicsIt-Networks

**Comment by Algalish** [comment]
done in V.11
