### ISSUE TITLE
Add information display

### ISSUE THREAD

**Issue by DesktopMan** [Algalish/SmartIssueTracker#42]
A small text window in a corner with the following information would be very useful:

* Dimensions of what you are building in number of buildings
* Dimensions of what you are building in meters
* Lowest elevation of what you are building in meters
* Highest elevation of what you are building in meters

The display could be expanded with more information as deemed useful. This is the idea I pitched to you on Discord, so you have it in writing.

**Comment by Algalish** [comment]
@DesktopMan  As a start we can show the dimensions in the top right corner as per this screenshot.  This will be shown ONLY if we changed the dimension from 1x1 to something else. 
Maybe the format can be changed in settings since not everyone will need size in meters and elevation.
Or maybe one of the formats will be a long one with all the data.

![Screenshot_1](https://user-images.githubusercontent.com/1682176/99179454-fd80fd00-272e-11eb-8d2d-cbc5ba9bf781.png)

**Comment by Algalish** [comment]
@DesktopMan  First version of that is done in V.8 but it will evolve and I will add more infor there as you asked

**Comment by nclow** [comment]
Looks pretty slick, but for me on 136408 with 0.9.0 the game's build number overlaps the information from Smart

https://imgur.com/a/gDiEcrJ

**Comment by Algalish** [comment]
This was done a long time ago, closing
