### ISSUE TITLE
Crash With Version 0.9.0 on multi-player game

### ISSUE THREAD

**Issue by Lordnms** [Algalish/SmartIssueTracker#63]

**Comment by Lordnms** [comment]
Hi
I have the problem when my freind Hosts a Game and I will join him that my Game crashes 
When we remove your Mod i Can join and play

**Comment by Barryt06** [comment]
Hi, 

Having the same issue.

![image](https://user-images.githubusercontent.com/1630560/100265992-f933bb80-2f48-11eb-9d4f-60f0c579c844.png)

Downgrading to 0.8.0 on both host and client fixed it.

**Comment by Lordnms** [comment]
OK this works for us too thx

**Comment by Shad0wlife** [comment]
Well, if I had refreshed the page, I could have avoided the duplicate comment in #53 . Oops.

**Comment by Charlie7887** [comment]
V.9 is not working in multiplayer for me and my girlfriend              V.8 works fine

**Comment by Algalish** [comment]
@Barryt06 @Shad0wlife @Lordnms @Charlie7887 
The last version broke MultiPlayer. Spent half a day trying to figure out a fix with gelp from other experience Satisfactory mod devs no luck. Need to work and will have a look at that tomorrow.
My appologies for the inconvinience , you can use previous version of the mod for now.
Oh, and if you remove the mod completely from the game - 0 buildings or foundations will be lost in saves. the mod is designed to be   "plug-and-play"

**Comment by HijackHornet** [comment]
Doesnt seems to work with 0.8 either for me :/ Waiting for the update

**Comment by Algalish** [comment]
@HijackHornet  I was completely overrun with work. Plan to do an update within the next 6-7 hours.

**Comment by Algalish** [comment]
@Barryt06 @HijackHornet @Shad0wlife @Lordnms 

Multi-player was actually a rebit hold that I went to.
Not only it was crashing but stuff like settings was not working fine. 
1)When opening settings on the clien it was opennning on the server
2) When client was building - the UI with build size was shown on a server!
3) when client was building in hold mode and was looking at the sky or other building - the foundation was placed incorrectly or not placed at all
4) when different settings of the mod were on server and on client - other problems appeared
5) crashes when joining and leaving for several times
I had to rework A HUGE part of the mod in order to get it all right.

Please, make a MP test as hard as you can guys, before I release an update.
Joining, leaving, buinding with different settings and modes on client and on the server, changing settings. all that stuff in otder to get the bug(like building one thing and then seing another) or make the game crash.

Thank you in advance.

P.S.  you can now open mode settings by just pressing M(short for menu) when you are building something with the mod. thats much easyer then just typeing "smartsmart"

P.P.S: rename .zip to .smod because github does not allow uploading of .smod
[Smart!-0.10.0.zip](https://github.com/Algalish/SmartIssueTracker/files/5612179/Smart.-0.10.0.zip)

**Comment by Algalish** [comment]
its all working now, V.10 is uploaded. let me know if there are any more issues
